### ISSUE TITLE
Getting the wrong wikipedia url starting from wikibase ID

### ISSUE THREAD

**Issue by seansay** [siznax/wptools#101]
Hi @siznax ,

Report a potential bug here.. this seems to work before.

I have a wikidata id of an [human](https://www.wikidata.org/wiki/Q722658), which I'll try to get the human chinese wikipedia page(which doesn't exist actually)..

The code I have is now something like

```
 p = wptools.page(wikibase='Q722658',  lang='zh', variant='zh-cn', skip='imageinfo')
In [53]: p.get()
www.wikidata.org (wikidata) Q722658
www.wikidata.org (labels) P646|P413|Q5|Q14565199|P641|Q1007418|P3...
zh.wikipedia.org (query) 679423
API warning: {u'main': {u'warnings': u'Unrecognized parameter: variant.'}}
zh.wikipedia.org (parse) 679423
API warning: {u'main': {u'warnings': u'Unrecognized parameter: variant.'}}
zh.wikipedia.org (restbase) /page/summary/User talk:B166991687
User talk:B166991687 (zh) data
{
  claims: <dict(26)> P646, P413, P734, P735, P641, P373, P2067, P4...
  exhtml: <str(94)> <p>感謝您對維基百科的興趣與貢獻，希望您會喜歡這裡。除了<b>歡迎辭</b>外，也請您了解...
  exrest: <str(77)> 感謝您對維基百科的興趣與貢獻，希望您會喜歡這裡。除了歡迎辭外，也請您了解以下重要文章：希望您...
  extext: <str(131)> 感谢您对维基百科的兴趣与贡献，希望您会喜欢这里。除了**欢迎辞**外，也请您了解以下重要文...
  extract: <str(149)> <p>感谢您对维基百科的兴趣与贡献，希望您会喜欢这里。除了<b>欢迎辞</b>外，也请您...
  labels: <dict(41)> P646, P413, Q5, Q211872, P641, Q1007418, P373...
  length: 2,713
  modified: <dict(2)> wikidata, page
  pageid: 679423
  parsetree: <str(2426)> <root>&lt;div style=&quot;width: 100%; ma...
  random: 茚满醇脱氢酶
  requests: <list(5)> wikidata, labels, query, parse, restbase
  title: User_talk:B166991687
  url: https://zh.wikipedia.org/wiki/User talk:B166991687
  url_raw: https://zh.wikipedia.org/wiki/User talk:B166991687?acti...
  what: 人类
  wikibase: Q722658
  wikidata: <dict(12)> 奖项 (P166), Freebase ID (P646), 图像 (P18), 性别...
  wikidata_url: https://www.wikidata.org/wiki/Q722658
  wikitext: <str(2011)> <div style="width: 100%; margin: 0.2em 0; ...
}
```

And somehow it gets to a User talk page on the chinese wiki,   it works fine with a wikidata id with a chinese wiki link... doesn't sure which the problem here is , should I use some check or the url here maybe should be empty?

Thanks!

**Comment by siznax** [comment]
Hey @seansay! Thanks for opening an issue. 

Because we start only with a `wikibase` ID here, the `page.get()` method has to ask Wikidata for info first. Wikidata doesn't offer a Chinese title for that item, which you can see is missing from that [Wikidata page](https://www.wikidata.org/wiki/Q722658), but it does find `pageid: 679423`. That is the Wikidata page ID. You can verify that on the [Wikidata info page](https://www.wikidata.org/w/index.php?title=Q722658&action=info) for that item.

Without a title, the next request will fall back on **pageid** as the search parameter, which in this case corresponds to a Talk page on `zh.wikipedia.org`. You can verify this on its [(zh) Wikipedia info page](https://zh.wikipedia.org/w/index.php?title=User_talk:B166991687&action=info).

I think what normally works for you is that you can give a `wikibase` ID and get a (simplified) Chinese title, and then get `zh-cn` variant page data from that title—(even though the API claims that the variant parameter is "Unrecognized")—but not in this case. 

The Wikidata page for [Q722658](https://www.wikidata.org/wiki/Q722658) also shows us that there is no `zh` Wikipedia entry (in the "Wikipedia" box near the bottom). So, you're not currently going to find any Chinese Wikipedia page info for that Wikidata item.

To catch this problem, you could separate your calls (e.g. `get_wikidata()`, `get_query()`, etc.) and verify that you have a title from Wikidata (`get_wikidata()`) before you make any more calls for page info.

Alternatively, we could put Wikidata page IDs in a different data member, like "`wikidata_pageid: 679423`", and then you would get `ValueError: get_query needs title or pageid` on the next call.

What do you think?

**Comment by seansay** [comment]
@siznax 

Hi Steve. Thanks so much for the help here!


> To catch this problem, you could separate your calls (e.g. get_wikidata(), get_query(), etc.) and verify that you have a title from Wikidata (get_wikidata()) before you make any more calls for page info.

Yes! This approach sounds good to me,  is something like this right?

```
p = wptools.page(wikibase='Q722658',  lang='zh', variant='zh-cn', skip='imageinfo')
p.get_wikidata()
 # prevent from goes to the wrong pag
assert p.data['label']

p.get()
# then I'll use the wikitext
print(p.data['wikitext'])

```

> Without a title, the next request will fall back on pageid as the search parameter, which in this case corresponds to a Talk page on zh.wikipedia.org. You can verify this on its (zh) Wikipedia info page.


To be honest I'm little confused here...
Is `pageid` something not global (like wikidata id), but local to the wikimedia instance?   If so, maybe we shouldn't use the wikidata page id to call the zhwiki's api?

**Comment by siznax** [comment]
That's right @seansay. The Wikidata page ID is different from the Wikipedia page ID, e.g.:

* Q42 has [Wikidata pageid: 138](https://www.wikidata.org/w/index.php?title=Q42&action=info)
* Q42 has [zhwiki pageid: 120400](https://zh.wikipedia.org/w/index.php?title=%E9%81%93%E6%A0%BC%E6%8B%89%E6%96%AF%C2%B7%E4%BA%9A%E5%BD%93%E6%96%AF&action=info)

And, you are right. We should not use the Wikidata page ID to call zhwiki's api.

So, I propose we put the Wikidata page ID in `page.data['wikidata_pageid']`.

**Comment by siznax** [comment]
Commit 3727904 should fix this @seansay 

```python
>>> page = wptools.page(wikibase='Q722658',  lang='zh', variant='zh-cn', skip='imageinfo')
>>> page.get_wikidata()
www.wikidata.org (wikidata) Q722658
www.wikidata.org (labels) P423|Q3811603|P735|Q5|Q1007418|P166|Q16...
+ skipping imageinfo
None (zh) data
{
  claims: <dict(26)> P21, P54, P569, P31, P18, P646, P27, P106, P3...
  image: <list(1)> {'file': 'File:Justin Williams.JPG', 'kind': 'w...
  labels: <dict(41)> P423, Q3811603, P735, Q5, Q1007418, P166, Q16...
  modified: <dict(1)> wikidata
  requests: <list(2)> wikidata, labels
  what: 人类
  wikibase: Q722658
  wikidata: <dict(12)> 性别 (P21), 所属运动队 (P54), 出生日期 (P569), 性质 (P31...
  wikidata_pageid: 679423
  wikidata_url: https://www.wikidata.org/wiki/Q722658
}
>>> page.data['wikidata_pageid']
679423
```

You can `assert 'title' in page.data` after calling `get_wikidata()`, or catch `ValueError` on the subsequent `get_query()`.

```python
>>> page.get_query()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/steve/Code/wptools/wptools/page.py", line 574, in get_query
    raise ValueError("get_query needs title or pageid")
ValueError: get_query needs title or pageid
```

**Comment by siznax** [comment]
I'm closing this to include in the next release. @seansay, feel free to re-open if this does not work for you. Thanks again for reporting this!
