### ISSUE TITLE
How to supress console output

### ISSUE THREAD

**Issue by TeCoGenie** [siznax/wptools#134]
Every time I make a query, the object is printed to the console. How can I turn off theese debug messages?

**Comment by siznax** [comment]
Thanks for trying wptools, @TeCoGenie!

Please take a look at our [usage](https://github.com/siznax/wptools/wiki/Usage) examples in the wiki. You can use the `silent=True` flag to suppress the `show()` command:

```
>>> import wptools
>>> page = wptools.page(silent=True)
>>> page.get_query().get_post()
<wptools.page.WPToolsPage object at 0x10c254e10>
```

However, the object will be printed to the python console after a query because the query has returned the calling object, which allows us to "chain" queries together (as shown above).

**Comment by TeCoGenie** [comment]
Thank you. That is what I needed!
