### ISSUE TITLE
Multiprocessing / Multithreading support

### ISSUE THREAD

**Issue by TheAmenRa** [siznax/wptools#141]
Hello, I'm considering this tool for research purpose and I'm wondering if I can use it with multiprocessing/multithreading in order to send multiple requests in parallel.

Is any protection against having the IP banned or stopped for a while implemented in some part of the code?

If no, should I care about it and put a delay in a parallelized request pipeline or avoiding it at all?

Thanks

**Comment by siznax** [comment]
Thanks for considering wptools @TheAmenRa! There is no protection in wptools against being banned. We do not support parallel requests in order to avoid issues. Please see: https://www.mediawiki.org/wiki/API:Etiquette

That said, there is nothing stopping you from making parallel requests. 😬 Please patch the user-agent with your contact info.

Alternatively, you can process dumps at your own pace: https://dumps.wikimedia.org/
