### ISSUE TITLE
feature request: get all disambiguation results

### ISSUE THREAD

**Issue by seansay** [siznax/wptools#25]
Hi Steve, 

Not sure this can be done now

When I rencounter a disambiguation page in `get_wikidata()`, I want to get all the page in the disambiguation. And then decide which one is what I want( by looking up it's wikidata claims maybe)

**Comment by siznax** [comment]
Hi @seansay. Thanks for the request. I'm not familiar with disclaimers. Can you give me an example?

**Comment by seansay** [comment]
for example, for the word `Phew`, in the english wikipedia it has many page related to this word https://en.wikipedia.org/wiki/Phew

so 
```
>> wptools.page('Phew', lang='en').get_wikidata()
Phew (en)
{
  lang: en
  title: Phew
}
en.wikipedia.org (action=wikidata) Phew
en.wikipedia.org (action=wikidata) Q4167410
Phew (en)
{
  claims: <dict(1)> {Q4167410}
  description: Wikipedia disambiguation page
  g_claims: <dict(3)> {info, query, response}
  g_wikidata: <dict(3)> {info, query, response}
  label: Phew
  lang: en
  props: <dict(1)> {P31}
  title: Phew
  wikibase: https://www.wikidata.org/wiki/Q7181489
  wikidata: <dict(1)> {instance}
```

in this case, I want to get all the pages. I suppose it should be done by parsing the page content,  so you can get all the links 

```
Phew may refer to:

Phew (singer), a Japanese vocalist
King Phew, a character from The Illmoor Chronicles
Kung Phews, a race originating from Chi Fang from the video game Serious Sam II
Phew, 1974 solo album by Claudia Lennear
```

**Comment by seansay** [comment]
Hi Steve,
sorry for my typo, I want to mean `disambiguation` instead of `disclaimers`.

**Comment by siznax** [comment]
Hi @seansay. Thanks for the request. No problem on the typo. I'm afraid this request is out of scope. Getting redirected to a disambiguation page is a valid use case, and external tools should handle crawling and scraping.

If this tools gains a solid user base and the request is re-opened, then it may be worth adding a separate module for things like this.

**Comment by siznax** [comment]
@seansay, I think I see the problem now. Even if you have identified a page by wikibase, the title gotten may lead to a disambiguation page! So, the tool should try to get the exact title from `sitelinks` in a `get_wikidata` request rather than from the `label`. 

For example:

```python
>>> phew = wptools.page(wikibase='Q528917').get_wikidata()
www.wikidata.org (action=wikidata) Q528917
www.wikidata.org (action=wikidata) Q17|Q5|Q11399
Q528917 (en)
{
  description: singer
  label: Phew
  lang: en
  title: Phew
  wikibase: Q528917
  ...
}
```

The title we need can be found in the API result (that is "Phew (singer)" rather than just "Phew"):

```
            "sitelinks": {
...
                "enwiki": {
                    "site": "enwiki",
                    "title": "Phew (singer)",
                    "badges": []
                },
```

I have a fix ready for this and will push to close (again).

**Comment by siznax** [comment]
Fix df3c63439f7d8b76f02ea7077a253c290d32ec19 ensures that we get an unambiguous title from Wikidata from `sitelinks`:

```python
>>> phew = wptools.page(wikibase='Q528917').get()
www.wikidata.org (action=wikidata) Q528917
www.wikidata.org (action=wikidata) Q17|Q5|Q11399
en.wikipedia.org (action=query) Phew_(singer)
en.wikipedia.org (action=parse) 20974062
Q528917 (en)
{
  description: singer
  extext: <str(472)> **Phew** (born in September 12, 1959) is a Japa...
  title: Phew_(singer)
  url: https://en.wikipedia.org/wiki/Phew_(singer)
  wikibase: Q528917
  ...
}
```

**Comment by seansay** [comment]
@siznax 
oh,  actually this is not what i'm asking for.  But maybe this is what it should be (setting the right title for disambiguation page).

I think I don't have this problem because I always query wikipedia page by wikidata id, that way wikipedia content is correct as expected.

**Comment by typistX** [comment]
I think what @seansay meant, and what someone like me came here looking for, is a way to "choose" from disambiguation options.

For example, if I search for "Everest" looking for the music band, `wptools.page('Everest')` will naturally give me the mountain, but if I'm letting a third party use this to only search for music bands, for example, I don't want him to get the wrong page. Is there a way around this?

**Comment by siznax** [comment]
Thanks for the comment, @typistX. We need to find a machine readable disambiguation result from the APIs and put that in something like ``page.data['disambiguation']`` when appropriate. I'll look into it.

**Comment by seansay** [comment]
Thanks @typistX for the comment, I think what you mentioned it's the same problem I have. My initial task is to bind our local music database with the wikidata artist, so when I use `wptools.page('Phew', lang='en').`, if there's only one page then it's easier, but if it's a disambiguation page matches multi wikipedia pages then I need to iterate all the pages to find the correct one. 

(It's been a year since this issue opened!)

**Comment by siznax** [comment]
Hehe, it has been a year, @seansay—time flies! Thanks again @typistX for reminding me to look again for a solution. 

**Potential solutions**

In the "Phew" case, we get an obvious disambiguation result. In the "Everest" case, we get redirected. We need one of the following:

1. A MediaWiki API endpoint yielding redirect or disambiguation page candidates with page ids,
2. A disambiguation page parser we can call when we get disambiguated, or
3. Logic that says: if we get redirected or disambiguated, then make another API call to search for something else (I don't know what).

I think (1) would be best, and we could probably implement (2) though it may not be a good idea, and (3) makes my brain hurt.

The difficulty with this issue is that it is a _search_ issue. Our tool assumes you know what you're looking for, or don't mind being redirected when giving a potentially ambiguous title. This avoids trying to recreate or second-guess MediaWiki search features, and keeps the tool simple and focused. There are many ways of finding unambiguous identifiers (page id, Wikidata id, unambiguous title, etc.) outside of this tool, and getting redirected or a disambiguation page are valid use cases too.

If you get a disambiguation page, you may already have the answer you want, e.g.:

```python
>>> phew = wptools.page('Phew').get_query()
en.wikipedia.org (query) Phew
Phew (en) data
{
  description: Wikipedia disambiguation page
...
}
>>> print phew.data['extext']
**Phew** may refer to:

  * Phew (singer), a Japanese vocalist
  * King Phew, a character from The Illmoor Chronicles
  * Kung Phews, a race originating from Chi Fang from the video game Serious Sam II
  * Phew, 1974 solo album by Claudia Lennear
```

Compare to [Phew disambiguation page](https://en.wikipedia.org/wiki/Phew) and checkout page [data captured](https://github.com/siznax/wptools/wiki/Data-captured) in other formats.

This article on [the distribution of disambiguation page links](http://www.slate.com/blogs/future_tense/2014/05/30/longest_disambiguation_pages_on_wikipedia_an_investigation.html) on English Wikipedia suggests that just using the "extract" text of a disambiguation page will be sufficient in most cases.

**Disambiguating bands**

You may have noticed that the MediaWiki convention for disambiguating things like music bands is to put "(band)" after the title. In the case of "Everest", ``wptools.page('Everest (band)')`` may be the result you want. So, if you got redirected you may want to try again by adding " (band)". This doesn't always work. I believe the wanted "Phew" result is given by 'Phew (singer)'.

In this context, you may have more success adding potentially disambiguating suffixes like "(album)", "(band)", "(musician)", etc.—there probably aren't too many—and offer those choices to your users instead of irrelevant disambiguation page list items.

If you want unambiguous identifiers for "music bands" that contain certain words, then you can probably [use the Wikidata Query Service](https://www.mediawiki.org/wiki/Wikidata_query_service/User_Manual) to generate ids. That points in the direction of solution (3), but if you got real confident about your data, then you could redirect your users to some of those results.

**Onward**

I'm still looking for solution (1). Solution (2) _seems_ helpful but steers us in the direction of writing yet another parser. I don't think any of the solutions will help with redirects, however.

@typistX, if there are times you don't want to be redirected, then we could add a switch to turn that off, and you could get a ``LookupError`` instead. If you want that, please open a new issue. However, the ``page.data['title']`` member gives you a clue. If it is different from your input title, then you've been redirected.

@seansay, if you have already written a disambiguation page parser, please share! We could add the parsing bit to ``wptools.utils`` and add another API call to get the page contents (or reuse ``get_restbase('html')``), and use your parser on that result.

Sorry this comment is so long. I'm honestly trying to be helpful! 😄

**Comment by siznax** [comment]
The [Extension:Disambiguator](https://www.mediawiki.org/wiki/Extension:Disambiguator) does not currently support what we need, but there is a phabricator task that sounds promising: [T161349: Provide a structured way to represent disambiguation pages and give API responses](https://phabricator.wikimedia.org/T161349). It was opened on 24 March 2017. Hopefully there will be some progress on it.

In the meantime, it looks like we can use [API:Links](https://www.mediawiki.org/wiki/API:Links) on disambiguation pages.

**Comment by siznax** [comment]
Using [Extension:Disambiguator](https://www.mediawiki.org/wiki/Extension:Disambiguator) and [API:Links](https://www.mediawiki.org/wiki/API:Links), we can get the disambiguation page links as titles (filtering on ns=0, or articles only) and indicate clearly that the result is a disambiguation with a ``page.data['disambiguation']`` member where I put the number of links:

```python
>>> phew = wptools.page('Phew')
>>> phew.get()
...

>>> phew.data['disambiguation']
6

>>> phew.data['links']
[u'Claudia Lennear',
 u'List of characters in Serious Sam II',
 u'PU (disambiguation)',
 u'Phew (singer)',
 u'The Illmoor Chronicles',
 u'Whew (disambiguation)']
```

It would be better if we could get the link page ids, but that's all I've been able to find. Also, we can only get up to 500. The article I referenced above says the top 4 disambiguation pages had over 500 links.

```python
>>> ali = wptools.page('Aliabad')
>>> ali.get()
...

>>> ali.data['disambiguation']
500

>>> ali.data['links'][:5]
[u"'Aliabad",
 u'Abkuh Aliabad',
 u'Ali Abad District',
 u'Ali Abadak, Razavi Khorasan',
 u'Aliabad (27\xb026\u2032 N 53\xb029\u2032 E), Gerash']
```

@seansay, will that work for you?

**Comment by siznax** [comment]
I've added a ``page.data['redirected']`` from [API:Redirects](https://www.mediawiki.org/wiki/API:Redirects) to indicate when we've been redirected. It's a list because our query may include multiple terms in the future:

```python
>>> page = wptools.page('Everest')
>>> page.get()
...

>>> page.data['redirected']
[
    {
        u'from': u'Everest',
        u'to': u'Mount Everest'
    }
]
```

@typistX, this will help you know when you've been redirected. If you then want to get disambiguation links, you can try another call with "(disambiguation)" appended to the original term, e.g.:

```python
>>> page = wptools.page('Everest (disambiguation)')
>>> page.get()
...

>>> page.data['disambiguation']
40

>>> page.data['links'][:10]
[u'Australian Turf Club',
 u'Barbara Everest',
 u'British American Tobacco',
 u'Club Deportivo Everest',
 u"Everest '82",
 u'Everest (1998 film)',
 u'Everest (2007 film)',
 u'Everest (2015 film)',
 u'Everest (Indian TV series)',
 u'Everest (band)']  # <============ here's your band!
```

I don't know how well that strategy will work for you, but it's all I can think of at the moment.

**Comment by siznax** [comment]
I've added ``page.data['disambiguation']``, ``page.data['links']``, ``page.data['redirected']``, and ``page.data['redirects']`` to the [Data captured](https://github.com/siznax/wptools/wiki/Data-captured) wiki page.

**Comment by siznax** [comment]
These features are now available in [0.4.1](https://github.com/siznax/wptools/releases/tag/0.4.1)

**Comment by siznax** [comment]
I'm going to call this done. We now have a reliable way to check for both disambiguation and redirection results, and we had some discussion about providing better disambiguation links.

**Comment by typistX** [comment]
Sorry for not being responsive. I'll get reading now. Thanks for dealing with this swiftly.
